### ISSUE TITLE
how to make it work with tag files?

### ISSUE THREAD

**Issue by henry-y** [abingham/emacs-ycmd#150]
Hi

I need help to make completion candidates include those in tag files.

While looking at ycmd.el, I see that collect_identifiers_from_tags_files is hardcoded to be 0, and I've changed it to 1, but nothing works.

All in all, I take the following steps to configure:
1. cd to project root.
2. ctags-exuberant -R
3. change collect_identifiers_from_tags_files in ycmd.el from 0 to 1.
4. type some charactor in emacs, and it won't display tag candidates, just those in current buffer.

and the *ycmd-server* output:

(Question can be turned off with options, see YCM docs)                                                                                                                        
2015-03-03 17:48:13,646 - INFO - Received extra conf load request                                                                                                              
2015-03-03 17:48:18,916 - INFO - Received event notification                                                                                                                   
2015-03-03 17:48:18,917 - DEBUG - Event name: FileReadyToParse                                                                                                                 
2015-03-03 17:48:18,917 - INFO - Adding buffer identifiers for file: /root/dev/testproj/main.c                                                
2015-03-03 17:48:23,163 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:23,164 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:23,399 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:23,400 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:24,036 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:24,036 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:24,181 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:24,182 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:24,331 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:24,332 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:24,471 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:24,471 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:25,768 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:25,769 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:26,056 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:26,056 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:26,176 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:26,176 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:26,260 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:26,261 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:29,324 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:29,325 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:29,490 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:29,490 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:29,767 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:29,768 - DEBUG - Using filetype completion: False                                                                                                             
2015-03-03 17:48:29,883 - INFO - Received completion request                                                                                                                   
2015-03-03 17:48:29,883 - DEBUG - Using filetype completion: False        

configure file is here:https://github.com/henry-y/.emacs.d/blob/master/.ycm_extra_conf.py

many thanks in advance!

**Comment by ptrv** [comment]
Hi,
the documentation of YouCompleteMe (https://github.com/Valloric/YouCompleteMe) says that you have to generate your tag files with `--fields=+l`. Did you try it?

**Comment by ptrv** [comment]
I quickly looked into this, but I think emacs-ycmd does not support tag files yet. I'll look into this feature as soon as possible.

**Comment by abingham** [comment]
Between steps 3 and 4 do you restart emacs or otherwise re-evaluate ` ycmd--options-contents`? Just changing the code without evaluating it won't produce any effect.

**Comment by ptrv** [comment]
@abingham I think you have to send the tag file names explicitly to the`ycmd` server.
@Valloric is this correct?

**Comment by henry-y** [comment]
@ptrv I tried --fields=+l, still not working
@abingham yes, I restart emacs, plus I also re byte compile the ycmd.el file to make sure

from ycmd's file identifier_completer.py, there's something about tag file names:

def OnFileReadyToParse( self, request_data ):                                                                                                                             self.AddBufferIdentifiers( request_data )                                                                                                                         if 'tag_files' in request_data:                                                                                                                                       self.AddIdentifiersFromTagFiles( request_data[ 'tag_files' ] ) 

but I don't know how to make emacs-ycmd pass this info to ycmd.

**Comment by ptrv** [comment]
See #151

**Comment by Valloric** [comment]
@ptrv Correct, you have to send the full paths to the tags files you want ycmd to read.

**Comment by henry-y** [comment]
@ptrv I've tried the new ycmd.el file, but can't get it work either.

I've set the ycmd-collect-identifiers-from-tags-file variable also

ycmd-collect-identifiers-from-tags-file is a variable defined in `ycmd.el'.           
Its value is t                                                                        
Original value was nil                                                                
                                                                                      
Documentation:                                                                        
Whether to collect identifiers from tags file.                                        
                                                                                      
You can customize this variable



ycmd-server output:


2015-03-05 12:52:15,918 - DEBUG - No global extra conf, not calling method YcmCorePre\
load                                                                                  
serving on http://127.0.0.1:34934                                                     
2015-03-05 12:52:15,954 - INFO - Received event notification                          
2015-03-05 12:52:15,954 - DEBUG - Event name: FileReadyToParse                        
2015-03-05 12:52:15,954 - INFO - Adding buffer identifiers for file: /root/dev/mc/src\
/mc_server/src/mc_server_logic.c                                                      
Traceback (most recent call last):                                                    
  File "/root/dev/ycmd/third_party/bottle/bottle.py", line 861, in _handle            
    return route.call(**args)                                                         
  File "/root/dev/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper           
    rv = callback(*a, **ka)                                                           
  File "/root/dev/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper         
    return callback( *args, **kwargs )                                                
  File "/root/dev/ycmd/ycmd/../ycmd/hmac_plugin.py", line 54, in wrapper              
    body = callback( *args, **kwargs )                                                
  File "/root/dev/ycmd/ycmd/../ycmd/handlers.py", line 70, in EventNotification       
    event_handler )( request_data )                                                   
  File "/root/dev/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 202, in \
OnFileReadyToParse                                                                    
    flags = self._FlagsForRequest( request_data )                                     
  File "/root/dev/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 265, in \
_FlagsForRequest                 
    return self._flags.FlagsForFile( filename, client_data = client_data )            
  File "/root/dev/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 56, in FlagsForFil\
e                                                                                     
    module = extra_conf_store.ModuleForSourceFile( filename )                         
  File "/root/dev/ycmd/ycmd/../ycmd/extra_conf_store.py", line 48, in ModuleForSource\
File                                                                                  
    return Load( ModuleFileForSourceFile( filename ) )                                
  File "/root/dev/ycmd/ycmd/../ycmd/extra_conf_store.py", line 59, in ModuleFileForSo\
urceFile                                                                              
    if Load( module_file ):                                                           
  File "/root/dev/ycmd/ycmd/../ycmd/extra_conf_store.py", line 134, in Load           
    if not _ShouldLoad( module_file ):                                                
  File "/root/dev/ycmd/ycmd/../ycmd/extra_conf_store.py", line 117, in _ShouldLoad    
    raise UnknownExtraConf( module_file )                                             
UnknownExtraConf: Found /root/dev/mc/.ycm_extra_conf.py. Load?                        
                                                                                      
(Question can be turned off with options, see YCM docs)                               
2015-03-05 12:52:16,727 - INFO - Received extra conf load request                     
2015-03-05 12:52:21,508 - INFO - Received event notification  
2015-03-05 12:52:21,508 - DEBUG - Event name: FileReadyToParse                        
2015-03-05 12:52:21,508 - INFO - Adding buffer identifiers for file: /root/dev/mc/src\
/mc_server/src/mc_server_logic.c                                                      
2015-03-05 12:52:22,512 - INFO - Received completion request                          
2015-03-05 12:52:22,512 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:23,316 - INFO - Received completion request                          
2015-03-05 12:52:23,321 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:24,104 - INFO - Received completion request                          
2015-03-05 12:52:24,105 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:25,246 - INFO - Received completion request                          
2015-03-05 12:52:25,247 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:25,409 - INFO - Received completion request                          
2015-03-05 12:52:25,410 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:26,379 - INFO - Received completion request                          
2015-03-05 12:52:26,380 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:26,769 - INFO - Received completion request                          
2015-03-05 12:52:26,769 - DEBUG - Using filetype completion: False                    
2015-03-05 12:52:34,437 - INFO - Received completion request                          
2015-03-05 12:52:34,437 - DEBUG - Using filetype completion: False
