### ISSUE TITLE
Ycmd sever timeout

### ISSUE THREAD

**Issue by zhuzhongshu** [abingham/emacs-ycmd#267]
I can't start the ycmd server after update my ycmd server and emacs-ycmd package. The error message is as follow:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zzs/.emacs.d/ycmd/ycmd/__main__.py", line 22, in <module>
    from future import standard_library
ImportError: No module named future

Process ycmd-server exited abnormally with code 1

**Comment by abingham** [comment]
This is some problem with your ycmd installation, not emacs-ycmd. Back in 31.1.2016 ycmd introduced a dependency on python-future, apparently bringing it in via git submodules. Perhaps you need to do a "git submodule update".
