### ISSUE TITLE
Debugging emacs-ycmd

### ISSUE THREAD

**Issue by paul-g** [abingham/emacs-ycmd#270]
Hi, 

I have issues when requesting completions from spacemacs:

```
<h1>Critical error while processing request: /event_notification</h1>2016-02-26 11:38:52,630 - ERROR - Exception when serving /event_notification
Traceback (most recent call last):
  File "/home/paul-g/workspaces/ycmd/third_party/waitress/waitress/channel.py", line 337, in service
    task.service()
  File "/home/paul-g/workspaces/ycmd/third_party/waitress/waitress/task.py", line 173, in service
    self.execute()
  File "/home/paul-g/workspaces/ycmd/third_party/waitress/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/paul-g/workspaces/ycmd/third_party/bottle/bottle.py", line 977, in __call__
    return self.wsgi(environ, start_response)
  File "/home/paul-g/workspaces/ycmd/third_party/bottle/bottle.py", line 972, in wsgi
    start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
  File "/home/paul-g/workspaces/ycmd/third_party/waitress/waitress/task.py", line 354, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/paul-g/workspaces/ycmd/third_party/bottle/bottle.py", line 958, in wsgi
    start_response(response._status_line, response.headerlist)
  File "/home/paul-g/workspaces/ycmd/third_party/waitress/waitress/task.py", line 372, in start_response
    'Header name %r is not a string in %r' % (k, (k, v))
AssertionError: Header name u'X-Ycm-Hmac' is not a string in (u'X-Ycm-Hmac', 'mZwzjwAj+LXx7y0FES+2q9n/zB0UNjDYRI2roVMGHsg=')
```

Any ideas what might be causing this? It seems like there might be a mismatch between the ycmd-server & client protocol? From the docs of emacs-ycmd I can't figure out exactly what revision of ycmd emacs-ycmd expects me to install (I am using 7a105f5 ATM). I also reported this on the [spacemacs tracker](https://github.com/syl20bnr/spacemacs/issues/5134).

**Comment by ptrv** [comment]
This is an issue with `ycmd` which already have been solved. https://github.com/Valloric/ycmd/issues/377

The protocol has not been changed so latest emacs-ycmd and latest `ycmd` works.

**Comment by paul-g** [comment]
Yes, this worked for me. Thanks!

**Comment by ptrv** [comment]
I am glad your issue could be solved.
