### ISSUE TITLE
Process ycmd-server exited abnormally with code 2

### ISSUE THREAD

**Issue by Sn0rt** [abingham/emacs-ycmd#300]
error message is 
```lisp
2016-05-01 22:25:56,208 - DEBUG - Global extra conf not loaded or no function YcmCorePreload

Process ycmd-server exited abnormally with code 2


```
my .spacemacs follow: 
```lisp
(set-variable 'ycmd-server-command '("python2" "/home/guowang/workspace/ycmd/ycmd"))
(set-variable 'ycmd-global-config "/home/guowang/.emacs.d/layers/+tools/ycmd/global_conf.py" )
(add-hook 'python-mode-hook 'ycmd-mode)
(add-hook 'c-mode-hook 'ycmd-mode)
```

```shell
➜  ~ ls workspace/ycmd/ycmd 
bottle_utils.py        handlers.py      identifier_utils.py    request_validation.pyc  server_state.pyc        utils.py
bottle_utils.pyc       handlers.pyc     identifier_utils.pyc   request_wrap.py         server_utils.py         utils.pyc
completers             hmac_plugin.py   __init__.py            request_wrap.pyc        server_utils.pyc        watchdog_plugin.py
default_settings.json  hmac_plugin.pyc  __init__.pyc           responses.py            tests                   watchdog_plugin.pyc
extra_conf_store.py    hmac_utils.py    __main__.py            responses.pyc           user_options_store.py
extra_conf_store.pyc   hmac_utils.pyc   request_validation.py  server_state.py         user_options_store.pyc
➜  ~ ls ~/.emacs.d/layers/+tools/ycmd 
global_conf.py  global_conf.pyc  packages.el  README.org

```

**Comment by abingham** [comment]
Does it work if you use python3 instead of 2? There have been some growing pains in ycmd lately with python2 vs. python3.

**Comment by Sn0rt** [comment]
I reinstall spacemacs and ycmd

python2

```python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/guowang/workspace/ycmd/ycmd/__main__.py", line 183, in <module>
    Main()
  File "/home/guowang/workspace/ycmd/ycmd/__main__.py", line 158, in Main
    extra_conf_store.CallGlobalExtraConfYcmCorePreloadIfExists()
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/extra_conf_store.py", line 73, in CallGlobalExtraConfYcmCorePreloadIfExists
    _CallGlobalExtraConfMethod( 'YcmCorePreload' )
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/extra_conf_store.py", line 91, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/extra_conf_store.py", line 149, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/utils.py", line 358, in LoadPythonSource
    return imp.load_source( name, pathname )
  File "/home/guowang/.emacs.d/layers/+tools/ycmd/global_conf.py", line 2, in <module>
    import ycm_core
ImportError: /home/guowang/workspace/ycmd/ycmd/../ycm_core.so: undefined symbol: clang_parseTranslationUnit2FullArgv

Process ycmd-server exited abnormally with code 1

```

python3 

```python
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/guowang/workspace/ycmd/ycmd/__main__.py", line 183, in <module>
    Main()
  File "/home/guowang/workspace/ycmd/ycmd/__main__.py", line 158, in Main
    extra_conf_store.CallGlobalExtraConfYcmCorePreloadIfExists()
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/extra_conf_store.py", line 73, in CallGlobalExtraConfYcmCorePreloadIfExists
    _CallGlobalExtraConfMethod( 'YcmCorePreload' )
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/extra_conf_store.py", line 91, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/extra_conf_store.py", line 149, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/home/guowang/workspace/ycmd/ycmd/../ycmd/utils.py", line 361, in LoadPythonSource
    return importlib.machinery.SourceFileLoader( name, pathname ).load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/guowang/.emacs.d/layers/+tools/ycmd/global_conf.py", line 2, in <module>
    import ycm_core
ImportError: /home/guowang/workspace/ycmd/ycmd/../ycm_core.so: undefined symbol: clang_parseTranslationUnit2FullArgv

Process ycmd-server exited abnormally with code 1
```

**Comment by abingham** [comment]
It doesn't seem like spacemacs, emacs, or emacs-ycmd is the problem here, so you shouldn't need to mess with those. The problem lies with how you've built or installed ycmd.

You should first ensure that ycmd can run at all, e.g. from the command line. If that doesn't work, then there's nothing that emacs-ycmd can do to help you.

**Comment by Sn0rt** [comment]
what's command can run ycmd in Terminal ?

**Comment by ptrv** [comment]
It looks like you compiled `ycmd` with system `libclang` and it is not matching with the `libclang` version needed to run `ycmd` (version 3.8)?

Please recompile ycmd using the libclang version shipped with `ycmd`

See here: https://bbs.archlinux.org/viewtopic.php?id=211069

**Comment by ptrv** [comment]
As @abingham already wrote this is not an issue with spacemacs, Emacs or emacs-ycmd.

**Comment by abingham** [comment]
@Sn0rt Regarding how to run ycmd on the command line, it's usually something like `python /some/path/top_of_ycmd_repo/ycmd <arguments>`. In your case you were trying `python2 /home/guowang/workspace/ycmd/ycmd`.

Note, though, that this will generally fail with an error since the server looks for a special temporary file (which it immediately deletes). But if your environment is OK then the failure will be something like "KeyError: 'hmac_secret'" rather than the `ImportError` you were seeing.

If you need more support for this, you should go to [the ycmd project](https://github.com/Valloric/ycmd).

**Comment by Sn0rt** [comment]
@abingham Thanks
