### ISSUE TITLE
Ycmd server error.

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#359]
This is my config.
```
(require 'ycmd)
(add-hook 'after-init-hook #'global-ycmd-mode)
(setq ycmd-toggle-force-semantic-completion t)
(set-variable 'ycmd-server-command
			  '("D:/appdata/emacs/extraBin/Python27" "-u" "D:/appdata/emacs/extraBin/ycmd/ycmd"))
```

The output is below.
```
File mode specification error: (error "Specified program for new process is a directory") 
apply: Specified program for new process is a directory
Error during redisplay: (eval prefer-utf-8-dos) signaled (void-variable prefer-utf-8-dos)
```

@abingham 
@Valloric 
@ptrv

**Comment by abingham** [comment]
Are you sure that `D:/appdata/emacs/extraBin/Python27` is a file and not a directory? The error you posted seems to indicate that it's a directory.

**Comment by moyotar** [comment]
It is a directory which contain python.exe.

**Comment by abingham** [comment]
Try `(set-variable 'ycmd-server-command '("D:/appdata/emacs/extraBin/Python27/python.exe" "-u" "D:/appdata/emacs/extraBin/ycmd/ycmd"))` instead. The `ycmd-server-command` needs to be an actual program, not just a directory containing a program.

**Comment by moyotar** [comment]
Thanks! A new problem: how to set ycmd-extra-conf-whitelist correctly?

**Comment by abingham** [comment]
That really depends on what you want to do. As [the documentation says](https://github.com/abingham/emacs-ycmd/blob/master/ycmd.el#L60), it's a list of glob patters. Whenever ycmd encounters an extra conf that matches one of those patterns, the extra conf is loaded without asking the user.

**Comment by moyotar** [comment]
I met this.

2016-09-29 15:48:12,936 - DEBUG - No global extra conf, not calling method YcmCorePreload
serving on http://127.0.0.1:62165
2016-09-29 15:48:13,167 - INFO - Received ready request
Traceback (most recent call last):
  File "D:\appdata\emacs\extraBin\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\appdata\emacs\extraBin\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\handlers.py", line 152, in GetReady
    return _JsonResponse( _IsSubserverReady( filetype ) )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\handlers.py", line 159, in _IsSubserverReady
    completer = _server_state.GetFiletypeCompleter( [filetype] )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\server_state.py", line 90, in GetFiletypeCompleter
    current_filetypes ) )
ValueError: No semantic completer exists for filetypes: [u'elisp']

**Comment by abingham** [comment]
You've got a cluster of issues here.

First, you've set `ycmd-toggle-force-semantic-completion` to `t`. This is wrong because `ycmd-toggle-force-semantic-completion` is a function...call it to toggle the value of `ycmd-force-semantic-completion`. If you want to simply force semantic completion all of the time, set `ycmd-force-semantic-completion` to `t`.

However, you're seeing he exception you've reported because you're trying to force semantic completion of emacs-lisp code (and all code, for that matter). Ycmd doesn't know how to do semantic completion of emacs lisp code.  

My suggestion is to set `ycmd-force-semantic-completion` to `nil`. Then you'll get identifier-based completion for code that ycmd doesn't have semantic support for.

**Comment by vheon** [comment]
@moyotar which is true (since ycmd doesn't have a semantic completer for elisp) so you will get the regular identifier completion. Don't you get any completion at all? Like with identifiers from the current file?

**Comment by moyotar** [comment]
@abingham  I follow your suggestion.  However,  I got this below when I tested completion in cpp file. 

2016-09-29 16:04:02,898 - DEBUG - No global extra conf, not calling method YcmCorePreload
serving on http://127.0.0.1:49682
2016-09-29 16:04:03,147 - INFO - Received ready request
2016-09-29 16:04:03,302 - INFO - Received event notification
2016-09-29 16:04:03,302 - DEBUG - Event name: BufferVisit
2016-09-29 16:04:03,397 - INFO - Received event notification
2016-09-29 16:04:03,398 - DEBUG - Event name: FileReadyToParse
2016-09-29 16:04:03,398 - INFO - Adding buffer identifiers for file: e:/download/P2P-master/P2P-master/P2PDemo/P2PClient/Client.cpp
Traceback (most recent call last):
  File "D:\appdata\emacs\extraBin\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\appdata\emacs\extraBin\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\handlers.py", line 67, in EventNotification
    event_handler )( request_data )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 319, in OnFileReadyToParse
    flags = self._FlagsForRequest( request_data )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 396, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "D:\appdata\emacs\extraBin\ycmd\ycmd\..\ycmd\completers\cpp\flags.py", line 86, in FlagsForFile
    raise NoExtraConfDetected
NoExtraConfDetected: No .ycm_extra_conf.py file detected, so no compile flags are available. Thus no semantic support for C/C++/ObjC/ObjC++. Go READ THE DOCS *NOW*, DON'T file a bug report.

And It naturally failed to complete.

**Comment by abingham** [comment]
Now you're trying to complete C++ code which *does* have semantic completion. Let me just point out the last line in the error trace:
```
NoExtraConfDetected: No .ycm_extra_conf.py file detected, so no compile flags are available. Thus no semantic support for C/C++/ObjC/ObjC++. Go READ THE DOCS NOW, DON'T file a bug report.
```
Please do that.

**Comment by moyotar** [comment]
@abingham  As for .ycm_extra_conf.py, I've added this in my config.
`(set-variable 'ycmd-global-config "D:/appdata/emacs/extraBin/ycmd/cpp/ycmd/.ycm_extra_conf.py")`

**Comment by abingham** [comment]
That's nice, but you need to [provide one for the specific "project" of the file you're working on](https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion). The global-config is a different thing from per-project configs. Please read the documentation thoroughly.
